config/routes.rb
TravelWeb::Application.routes.draw do

  resources :categories, only: [:index, :get]

  get "home" => "home#index"
  root :to => 'home#index'

end

app/models/attraction.rb
class Attraction
  attr_accessor :name, :snapshot_url

  def initialize(attrs = {} )
    attrs.each do |name, value|
      # calling the attr accessor
      self.send("#{name}=", value) if self.respond_to? "#{name}="
    end
  end


  def self.find_by_category(category_code, options = {})
    samples = [ { name: 'Sterling Winery', tag: ["sight"], snapshot_url: 'attractions/sterling-snapshot.jpg' },
                { name: 'Santana Row', snapshot_url: 'destinations/los-angeles-snapshot.jpg' },
                { name: 'San Diego', snapshot_url: 'destinations/san-francisco-snapshot.jpg' },
                { name: 'Las Vegas', snapshot_url: 'destinations/los-angeles-snapshot.jpg' },
                { name: 'San Luis Obispo', snapshot_url: 'destinations/san-francisco-snapshot.jpg' }]

    if options.include? :limit
      samples = samples.slice(0, options[:limit])
    end
    destinations = samples.map { |sample|  Attraction.new(sample)}
  end
end

app/models/category.rb
class Category
  attr_accessor :code, :description

  def initialize(attrs = {} )
    attrs.each do |name, value|
      # calling the attr accessor
      self.send("#{name}=", value) if self.respond_to? "#{name}="
    end
  end


  def self.find_suggested_list
    samples = [ { code: 'top', description: 'Most Popular' },
                { code: 'shopping', description: 'Shopping' },
                { code: 'recreational', description: 'Recreational Activities' },
                { code: 'sightseeing', description: 'Sightseeing' },
                { code: 'events', description: 'Events' }]

    destinations = samples.map { |sample|  Category.new(sample)}
  end
end

app/models/destination.rb
class Destination
  attr_accessor :name, :snapshot_url, :banner_image_urls

  def initialize(attrs = {} )
    attrs.each do |name, value|
      # calling the attr accessor
      self.send("#{name}=", value) if self.respond_to? "#{name}="
    end
  end


  def self.find_most_popular
    samples = [ { name: 'San Francisco', snapshot_url: 'destinations/san-francisco-snapshot.jpg' },
                { name: 'Los Angeles', snapshot_url: 'destinations/los-angeles-snapshot.jpg' },
                { name: 'San Diego', snapshot_url: 'destinations/san-francisco-snapshot.jpg' },
                { name: 'Las Vegas', snapshot_url: 'destinations/los-angeles-snapshot.jpg' },
                { name: 'San Luis Obispo', snapshot_url: 'destinations/san-francisco-snapshot.jpg' }]

    destinations = samples.map { |sample|  Destination.new(sample)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category_list = Category.find_suggested_list

    attractions = @category_list.map() { |category| [category.code, Attraction.find_by_category(category.code, limit: 3)] }
    @attractions_by_category = Hash[attractions]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @banner_images = ['home/homepage-1.jpg', 'home/homepage-2.jpg', 'home/homepage-3.jpg']
    @popular_destinations = Destination.find_most_popular()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def include_controller_javascript
    javascript_include_tag params[:controller] if Rails.application.assets.find_asset("#{params[:controller]}")
    # javascript_include_tag "#{params[:controller]}_#{params[:action]}" if OcCharts::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}")
  end

  def include_controller_stylesheet
    stylesheet_link_tag params[:controller] if Rails.application.assets.find_asset("#{params[:controller]}")
    # stylesheet_link_tag {params[:controller]}_#{params[:action]}" if OcCharts::Application.assets.find_asset("#{params[:controller]}_#{params[:action]}")
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attractions/_attraction.html.erb
<li class="span4">
  <a class="thumbnail">
    <%= image_tag attraction.snapshot_url %>
    <div class="caption">
      <p class="text-center"><%= attraction.name %></p>
    </div>
  </a>
</li>

app/views/categories/index.html.erb
<div class="row-fluid">
  <%= render 'wish_lists/wish_list' %>


  <div id="category-list" class="span9">

    <% @category_list.each do |category| %>
      <div id="category-container" class="container-fluid">
        <h4><%= category.code %></h4>

        <% @attractions_by_category[category.code].in_groups_of(3, false) do |attraction_row| %>
          <div class="row-fluid">
            <ul id="attraction-container" class="thumbnails well">
              <%= render partial: 'attractions/attraction', collection:  attraction_row %>
            </ul>
          </div>
          <div>
            <i class="icon-chevron-down"></i>
          </div>
        <% end # @attractions_by_category %>
      </div>
    <% end # @category_list %>
  </div>
</div>

app/views/destinations/_destination.html.erb
<li class="span4">
  <a class="thumbnail">
    <%= image_tag destination.snapshot_url %>
    <div class="caption">
      <p class="text-center"><%= destination.name %></p>
    </div>
  </a>
</li>

app/views/home/_banner_item.html.erb
<%
=begin
  expected parameters:
    - banner_item
=end
%>

<!-- snapshot -->

<div class="item <%= 'active' if banner_item_counter == 0 %>" >
  <%= image_tag banner_item %>

  <div class="carousel-caption">
    <h3 class="offset1">Simple yet Personal,</h3>
    <h3 class="offset2">How traveling should be</h3>
    <br></br>
    <div class="span4 offset4">
      <form class="navbar-search" action="#">

        <div>
          <div class="icon-search" ></div>
          <input class="input-large search-query align-center" type="text" placeholder="Destination" />
        </div>

      </form>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<div id="main-carousel" class="carousel side">
  <!-- carousel indicator -->
  <ol class="carousel-indicators">
    <% for banner_index  in 0..@banner_images.length - 1%>
      <% if banner_index == 0 %>
        <li data-target="#main-carousel" data-slide-to="<%= banner_index %>" class="active"></li>
      <% else %>
        <li data-target="#main-carousel" data-slide-to="<%= banner_index %>"></li>
      <% end %>
    <% end %>
  </ol>

  <!-- Carousel items -->
  <div class="carousel-inner">
    <%= render partial: 'banner_item', collection: @banner_images %>
  </div><!-- carousel-inner -->

  <!-- popular destinations -->
  <div id="destination-list" class="container-fluid">

    <% @popular_destinations.in_groups_of(3, false) do |destination_row| %>
      <div class="row-fluid">
        <ul class="thumbnails">
          <%= render partial: 'destinations/destination', collection: destination_row %>
        </ul>
      </div><!-- end destination row -->
    <% end %>
  </div>

  <%= render partial: 'users/login' %>

</div>

app/views/layouts/_error_messages.html.erb
<!--
  expected parameters:
    - model - active model
    - model_name - optional, default => model.class.model_name
 -->
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize model.errors.count, "error" %>
      prohibited this <%= model.class.model_name %> from being saved:
    </h2>
    <p>There were problems with the following fields: </p>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row-fluid">
  <nav class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <ul class="nav pull-right">
        <li><a href="#">Google+</a></li>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Blog</a></li>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="row-fluid">
  <div class="span12">
    <nav class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">Dream Trip</a>
        <ul class="nav">
          <li><%= link_to 'Home', home_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="#">Wish List</a></li>
          <li><a href="#sign-in" role="button" data-toggle="modal">Sign in</a></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelWeb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- controller specific javascript/stylesheet -->
  <%= include_controller_stylesheet %>

<!--
  <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet" media="screen" />
-->
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>

<body>
<div class="container-fluid">
  <!-- header -->
  <%= render 'layouts/header' %>

  <!-- main content -->
  <div class="row-fluid" id="main-content">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, :class => "alert alert-#{key}" %>
    <% end %>

    <%= yield %>
  </div>
  <!-- footer -->
  <%= render 'layouts/footer' %>
</div>

<!-- application javascripts -->
<%= javascript_include_tag "application" %>
<!-- controller specific javascripts -->
<%= include_controller_javascript %>
<!-- view specific javascripts -->
<%= yield :javascript_includes %>

<%= debug params if Rails.env.development? %>

</body>
</html>

app/views/users/_login.html.erb
      <div id="sign-in" class="modal hide fade" aria-labbelledby="modalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            <i class="icon-remove"></i>
          </button>
          <h3 id="modalLabel">Sign in</h3>
          
        </div>
        <div class="modal-body">
          <form>
            <input type="text" class="input-block-level" placeholder="email" />
            <input type="password" class="input-block-level" placeholder="password" />
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">cancel</button>
          <button class="btn btn-success">Sign in</button>
        </div>
        
      </div>

app/views/wish_lists/_wish_list.html.erb
<div id="wish-list" class="span2">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Wish List</li>
      <li>
        <a class="thumbnail">
          <%= image_tag "attractions/castle-winery-sonoma-snapshot.png" %>
          <div class="caption">
            <p class="text-center">Castle Winery</p>
          </div>
        </a>
      </li>
    </ul>
  </div>
</div>